---
image: python:3.6

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script: &tox_install
  - pip install tox

lint:
  script:
    - tox -e lint

typing:
  script:
    - tox -e typing

tests:
  before_script:
    - *tox_install
    - apt-get -q update
    - apt-get -y -q --no-install-recommends install postgresql
    - useradd --create-home gitlab
  script:
    - su -c "tox -e tests" gitlab
