---
image: python:3.6

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - apt-get -q update
  - apt-get -y -q --no-install-recommends install postgresql
  - pip install tox
  - useradd --create-home gitlab

lint:
  script:
    - tox -e lint

typing:
  script:
    - tox -e typing

tests:
  script:
    - su -c "tox -e tests" gitlab
