---
image: $CI_REGISTRY_IMAGE

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

lint:
  stage: test
  script:
    - tox -e lint

typing:
  stage: test
  script:
    - tox -e typing

tests:
  stage: test
  script:
    - tox -e tests

docs:
  stage: test
  script:
    - tox -e docs
  artifacts:
    paths: [docs/_build/]
    expire_in: 3 days

ci_image:
  stage: build
  image: docker:19.03-dind
  services:
    - docker:19.03-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd ci/testing
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
