---
stages:
  - tests

tests:
  stage: tests
  needs: []
  image: python:3.6
  before_script:
    - apt-get -q update
    - apt-get -y -q install postgresql
    - pip install tox
    - useradd gitlab
  script:
    - su -c tox gitlab
