---
- name: my postgresql instances
  hosts: localhost
  tasks:
    - name: production instance, dropped
      postgresql_instance:
        name: prod
        state: absent
    - name: drop backup schedule task
      cron:
        name: backup prod postgres
        state: absent

    - name: dev instance, dropped
      postgresql_instance:
        name: dev
        state: absent
