FROM debian:bullseye-slim
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq update && \
	apt-get -qq -y install --no-install-recommends \
	curl \
	ca-certificates \
	gnupg \
	lsb-release \
	&& rm -rf /var/lib/apt/lists/*
RUN echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -c -s)-pgdg main" \
	| tee /etc/apt/sources.list.d/pgdg.list
RUN curl --output /etc/apt/trusted.gpg.d/pgdg.asc https://www.postgresql.org/media/keys/ACCC4CF8.asc
RUN mkdir -p /etc/postgresql-common/createcluster.d/
RUN echo "create_main_cluster = false" \
	> /etc/postgresql-common/createcluster.d/no-main-cluster.conf
RUN apt-get -qq update && \
	apt-get -y install --no-install-recommends postgresql-common
RUN apt-get -qq update && \
	apt-get -y install --no-install-recommends \
	build-essential \
	git \
	procps \
	python3-pip \
	python3-venv \
	postgresql-14 \
	postgresql-14-pg-qualstats \
	postgresql-14-pg-stat-kcache \
	postgresql-14-powa \
	pgbackrest \
	prometheus-postgres-exporter \
	tox \
	&& rm -rf /var/lib/apt/lists/*

RUN useradd --create-home runner

USER runner
WORKDIR /home/runner
