FROM rockylinux:8
RUN dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
RUN dnf -qy module disable postgresql
RUN dnf install -y postgresql10-server postgresql10-contrib pg_stat_kcache10 pg_qualstats10 powa_10 pgbackrest
WORKDIR /tmp
ARG PGE_VERSION=0.10.1
ARG PGE_FNAME=postgres_exporter-${PGE_VERSION}.linux-amd64
ARG PGE_TGZ=${PGE_FNAME}.tar.gz
RUN curl -O -L \
	https://github.com/prometheus-community/postgres_exporter/releases/download/v${PGE_VERSION}/${PGE_TGZ}
RUN tar xvf ${PGE_TGZ}
RUN mv ${PGE_FNAME}/postgres_exporter /usr/bin/
RUN dnf install -y gcc git openssl procps-ng python3-pip

RUN pip3 install tox
RUN useradd --create-home runner

USER runner
WORKDIR /home/runner
ENV PATH=/usr/pgsql-10/bin:$PATH
